github:
  organisations:
    - name: iteratelabs
      repositories:
#         - name: full-chart
#           branch: main
#           useSinglePullRequest: true
        - name: terraform
          branch: main
          useSinglePullRequest: true
